// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6r8yUJz47syn5Tdv1ycQrezvVS3ymu3I',
    appId: '1:1011970288928:web:759c7661e183667612fb45',
    messagingSenderId: '1011970288928',
    projectId: 'flutter-noteapp-b6b87',
    authDomain: 'flutter-noteapp-b6b87.firebaseapp.com',
    storageBucket: 'flutter-noteapp-b6b87.firebasestorage.app',
    measurementId: 'G-Y3LKFJJ0KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WSjkMV_n5wtQSs3fnrMISbR0pW9OxCc',
    appId: '1:1011970288928:android:8beaa7879c5f83ea12fb45',
    messagingSenderId: '1011970288928',
    projectId: 'flutter-noteapp-b6b87',
    storageBucket: 'flutter-noteapp-b6b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XwDoIGsvVdLO4pZ6mjj-GHM630-L_Mw',
    appId: '1:1011970288928:ios:b170e7b79b6bbbed12fb45',
    messagingSenderId: '1011970288928',
    projectId: 'flutter-noteapp-b6b87',
    storageBucket: 'flutter-noteapp-b6b87.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XwDoIGsvVdLO4pZ6mjj-GHM630-L_Mw',
    appId: '1:1011970288928:ios:b170e7b79b6bbbed12fb45',
    messagingSenderId: '1011970288928',
    projectId: 'flutter-noteapp-b6b87',
    storageBucket: 'flutter-noteapp-b6b87.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6r8yUJz47syn5Tdv1ycQrezvVS3ymu3I',
    appId: '1:1011970288928:web:954e24417c0bd32912fb45',
    messagingSenderId: '1011970288928',
    projectId: 'flutter-noteapp-b6b87',
    authDomain: 'flutter-noteapp-b6b87.firebaseapp.com',
    storageBucket: 'flutter-noteapp-b6b87.firebasestorage.app',
    measurementId: 'G-9Z861NGTQ9',
  );
}
